eureka: 
  client: 
    enbaled: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/

zhb: 
  forever: 
    ms: 
      url: http://localhost:8012
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/zhb_springcloud?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 3000
    minIdle: 1
logging: 
  level: 
    ROOT: info


    
    
  