server:
  port: 8010
  tomcat:
      uri-encoding: UTF-8
spring:
  application:
    name: zhb-forever-config
  profiles: 
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZHB1024/front-back-end
          searchPaths: config
          basedir: D:/java/code/temp
          username: ZHB1024
          password: ZHB1024
logging:
  level:
    ROOT: info
    com.forever: debug
  file:
    log/zhb-forever-config.log		
  