server: 
  port: 8011
  tomcat: 
      uri-encoding: UTF-8
eureka: 
  client: 
    enbaled: true
    serviceUrl: 
      defaultZone: ${EUREKA_URL}
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/zhb_springcloud?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 3000
    minIdle: 1o
  http: 
    multipart: 
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  main: 
    allow-bean-definition-overriding: true
  flyway:
    locations: classpath:db
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_schema_history_server
logging: 
  level: 
    ROOT: info
  file: 
    log/zhb-forever-server.log		
mybatis: 
  configuration: 
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath*:mybatis/mapper/*.xml
feign: 
  hystrix: 
    enabled: true
zhb: 
  forever: 
    ms: 
      url: http://localhost:8012
    mail: 
      userName: ZHB1024
      password: 123456
logging: 
  level: 
    ROOT: inf