server: 
  port: 8012
  tomcat: 
      uri-encoding: UTF-8
eureka:
  client:
    enabled: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/zhb_springcloud?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: '{cipher}847e30e5fc95fd2a3f1d8d3e1db55170d96d711fb18d1996f1c58dad54b10d36'
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 3000
    minIdle: 1
logging: 
  level: 
    ROOT: info
  file: 
    log/zhb-forever-ms.log
  